# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# to reset password: htpasswd -s -b -n internal changeme
openshift_prometheus_htpasswd_auth: internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM=
openshift_prometheus_basic_auth_pass: changeme
extra_prometheus_hosts:

# Uncomment this if your cluster serves privately signed certificates
# custom_ca: true

deployment:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: pelorus
    app.kubernetes.io/version: v0.33.0

exporters:
  instances:
  - app_name: deploytime-exporter
    source_context_dir: exporters/
    extraEnv:
    - name: APP_FILE
      value: deploytime/app.py
    - name: LOG_LEVEL
      value: DEBUG
    - name: NAMESPACES
      value: mongo-persistent
    source_ref: refs/pull/$PULL_NUMBER/head
    source_url: $OPENSHIFT_BUILD_SOURCE
  - app_name: committime-exporter
    source_context_dir: exporters/
    extraEnv:
    - name: APP_FILE
      value: committime/app.py
    - name: LOG_LEVEL
      value: DEBUG
    - name: NAMESPACES
      value: mongo-persistent
    source_ref: refs/pull/$PULL_NUMBER/head
    source_url: $OPENSHIFT_BUILD_SOURCE
  - app_name: failure-exporter
    exporter_type: failure
    env_from_secrets:
    - jira-credentials
    env_from_configmaps:
    - pelorus-config
    - failuretime-config
    source_ref: refs/pull/$PULL_NUMBER/head
    source_url: $OPENSHIFT_BUILD_SOURCE
